export const coffeeData = [
  {
    id: 1,
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 7.9,
    classification: ['tradicional'],
    coffeeImage: 'coffee01.png',
    quantity: 0,
  },
  {
    id: 2,
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 7.9,
    classification: ['tradicional'],
    coffeeImage: 'coffee02.png',
    quantity: 0,
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 7.9,
    classification: ['tradicional'],
    coffeeImage: 'coffee03.png',
    quantity: 0,
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 7.9,
    classification: ['tradicional', 'gelado'],
    coffeeImage: 'coffee04.png',
    quantity: 0,
  },
  {
    id: 5,
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 8.5,
    classification: ['tradicional', 'com leite'],
    coffeeImage: 'coffee05.png',
    quantity: 0,
  },
  {
    id: 6,
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 8.5,
    classification: ['tradicional', 'com leite'],
    coffeeImage: 'coffee06.png',
    quantity: 0,
  },
  {
    id: 7,
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 8.5,
    classification: ['tradicional', 'com leite'],
    coffeeImage: 'coffee07.png',
    quantity: 0,
  },
  {
    id: 8,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 8.5,
    classification: ['tradicional', 'com leite'],
    coffeeImage: 'coffee08.png',
    quantity: 0,
  },
  {
    id: 9,
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 8.5,
    classification: ['tradicional', 'com leite'],
    coffeeImage: 'coffee09.png',
    quantity: 0,
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
    classification: ['especial', 'com leite'],
    coffeeImage: 'coffee10.png',
    quantity: 0,
  },
  {
    id: 11,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
    classification: ['especial', 'alcoólico', 'gelado'],
    coffeeImage: 'coffee11.png',
    quantity: 0,
  },
  {
    id: 12,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
    classification: ['especial'],
    coffeeImage: 'coffee12.png',
    quantity: 0,
  },
  {
    id: 13,
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
    classification: ['especial'],
    coffeeImage: 'coffee13.png',
    quantity: 0,
  },
  {
    id: 14,
    name: 'Árabe',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
    classification: ['especial'],
    coffeeImage: 'coffee14.png',
    quantity: 0,
  },
]
